[book]
title = "兩大類的學習筆記"
author = "兩大類"
language = "zh-tw"
multilingual = false
src = "src"

[output.html]
google-analytics = "G-RXCZ2T0M9G"
git-repository-url = "https://github.com/marco79423/study-notes"
